GET http://localhost:8080/api/viz/run-scenario

###
GET http://localhost:8080/api/tests/async-basic

###
GET http://localhost:8080/api/tests/exception-propagation

###
GET http://localhost:8080/api/viz/run-scenario
