GET http://localhost:8080/api/viz/one-launch-scenario

###
GET http://localhost:8080/api/viz/two-launch-scenario

###
GET http://localhost:8080/api/viz/nested-launch-scenario

###
GET http://localhost:8080/api/viz/run-scenario
